### ISSUE TITLE
specified key was too long

### ISSUE THREAD

**Issue by davisharry** [ant-vel/App#18] opened 2017-05-10 03:34 UTC
when i type 'php artisan migrate:refresh' , it shows "specified key was too long: max key length is 1000 bytes (SQL: alter table 'user' add unique 'users_nickname_unique')('nickname')".

**Comment by gocanto** [comment] 2017-05-10 03:41
Can you provide a screenshot? I would like to see the exception thrown. 

Thanks,

**Comment by davisharry** [comment] 2017-05-10 12:53
![antvel-error](https://cloud.githubusercontent.com/assets/24517852/25899494/ab26be2a-35c2-11e7-9345-4fef1be6ac56.png)

**Comment by gocanto** [comment] 2017-05-10 14:13
I know what the problem is in here. I need to fix the favtory that is used by the users seeder. I will be comminting a big update either today or tomorrow. I will make sure it fixes it.

**Comment by gocanto** [comment] 2017-05-12 05:07
it should be fixed by now https://github.com/ant-vel/App/commit/d04af2cd017aac4c331b742a942d7c2011a601a4

Let me know whether it worked for you.

Thanks for testing.

**Comment by davisharry** [comment] 2017-05-12 14:52
I've download the latest version but the same erroe appears.
I use wamp server 3.0.6 64bit  on WIN10.  apache 2.4  php 7.0 mysql 5.7.14
Last time i download code from https://github.com/ant-vel/antVel. it works.
But then  i found a new project here but i can not install. 
Could you please tell me how to install antvel, maybe i've missed something.

**Comment by gocanto** [comment] 2017-05-12 15:42
Thanks for reaching out. 

I am glad to help you out. Please, post the whole error thrown for me to understand what the problem is. 

Maybe we can figure this out toguether. 

Thanks

**Comment by gocanto** [comment] 2017-05-12 16:00
I want to keep the problem centralized here, 

https://github.com/ant-vel/App/issues/21

**Comment by davisharry** [comment] 2017-05-15 01:47
![antvel-error](https://cloud.githubusercontent.com/assets/24517852/26039980/826eb4bc-3953-11e7-9011-d207c0da2861.png)

**Comment by gocanto** [comment] 2017-05-16 03:09
I really tried to reproduce this bug but I was not successful at it. Can you please share more info? 

It would be nice if I could see a bigger scope.

Thanks.

**Comment by davisharry** [comment] 2017-05-30 06:29
![image](https://cloud.githubusercontent.com/assets/24517852/26570678/6615d898-4544-11e7-9bab-50d9b0a9c196.png)

**Comment by davisharry** [comment] 2017-05-30 06:36
Hi, last time the same error exists in table `users`  and now it has been fixed, but it shows up again in table `password_resets` . What about other tables, will the same error exits?

**Comment by gocanto** [comment] 2017-06-01 01:21
This commit might fix it.

https://github.com/ant-vel/App/commit/78ab354934ce02003a975aeed58028abffc84f3b

Thanks.

**Closed by gocanto** 2017-06-01 01:21 UTC
Labels: question
